### ISSUE TITLE
High CPU usage when viewing the Structure table type

### ISSUE THREAD

**Issue by 9a3eedi** [nasa/CCDD#104]
While following the tutorial, in the Table Type Editor. I noticed that when editing the Structure table type, and the Structure: Cmd Arg Ref, the java process CPU usage goes up to 100% and stays that way until you move to a different tab. It sounds like there's a thread that enters an infinite loop when it's not supposed to. This does not occur in the Command and ENUM tabs.

To recreate:
1. Open a project
2. Go to Data -> Manage Table Types
3. The Command tab will be shown. Observe the CPU usage of the java process being very low.
4. Switch to the ENUM tab, observe the CPU usage also being very low
5. Switch to the Structure tab. The CPU usage shoots up to 100% and stays that way.
6. Switch to the Structure: Cmd Arg Ref tab. the CPU usage stays up.
7. Switch back to either Command or ENUM, the cpu usage goes back to normal.

**Comment by KevinMcCluney** [comment]
The renderer for table header rows adjusts the font smaller if the column name occupies multiple lines. The current implementation sets up an infinite loop due to perceived height changes in the header each time the font changes. The structure table types have two multi-line column headers, which is why only those showed the excessive CPU usage.

The implementation will be changed in the next release so that the font sizing is made once when the renderer is assigned to the column (when the table is created).

**Comment by KevinMcCluney** [comment]
Version 2.1.5 addressed this issue.
