### ISSUE TITLE
C File ingest using structure type

### ISSUE THREAD

**Issue by mcirbo** [nasa/CCDD#108]
While ingesting the generic C files out of the box for CFE, I did not get all the commands ingested. Not sure if this is a bug or if this has a setting that need to be set. 

The issue, in more detail, is that there is a structure used to define a command with no arguments. That is then used to define several commands that have no parameters.
I.e. typedef CI_NoArgCmd_t CI_Noop;
However, the CI_Noop never makes it into the database after the C files are imported.

Thank you for the help

**Comment by KevinMcCluney** [comment]
I assume you are referring to using the **Data** | **Import data** | **C header** command to extract structure definitions from header files.  When importing, typedef statement in the form `typedef <current name> <newname>` are ignored (as in the example you gave: `typedef CI_NoArgCmd_t CI_Noop`) since this simply creates an alias for the structure _current_name_.  The only way CCDD could use this statement is to create a duplicate prototype structure (e.g., CI_Noop) which is not the same as the typedef alias.

**Comment by mcirbo** [comment]
Thank you for the quick response!
I think you answered this perfectly. So the way around this would be to either create each command as its own structure, or to manually edit the commands in CCDD for the names after importing the C headers right?
Could I also import the headers using the C header import command and then run them through another custom script to grab just those names from the header?

**Comment by KevinMcCluney** [comment]
You are correct, either the aliased structures have to be duplicated, or else the each reference to an alias must be changed to the actual (non-aliased) structure.
I'm not sure what you mean by your second question.

**Comment by thesamprice** [comment]
Just curious on the backend are you using llvm or gcc to parse the c code

**Comment by mcirbo** [comment]
I think my questions have been answered here. Thank you for all the help!

**Comment by KevinMcCluney** [comment]
Neither llvm or gcc is used to parse the C code.  It's done in CcddConvertCStructureToCSV.java.
