### ISSUE TITLE
Possibility of Compiling Locally, and How to?

### ISSUE THREAD

**Issue by mbulk-aero** [nasa/CCDD#114]
Hi all,
Thanks for all your work, am quite excited by this project.
I was wondering, is it possible to perform our own builds?

I mainly would like to do this, since have been unable to export as xtce or eds. When I click export for these file types, I select the table and path as needed, but nothing ever happens when I click export, and no logs or errors seem to show something out of the norm. 

I think though it may be something on my side, since have tried with multiple versions and have the same issue.

Thank you!

**Comment by KevinMcCluney** [comment]
To create the CCDD.jar file I use Ant from within Eclipse to execute the ccdd.build.xml script.  In Eclipse you can configure Ant from Window | Preferences | Ant.  

When an export completes there should be a message in the event log "Data export completed successfully) (Success messages must be enabled for viewing via the check box at the bottom of the main window in order to see them).  **At least one table must be selected in the table tree within the export dialog.**  Note the export path in the dialog - that's where the file(s) end up.  Make sure you have write permission to that folder.
