### ISSUE TITLE
Issues with Python script

### ISSUE THREAD

**Issue by kadri-nizam** [nasa/CCDD#115]
Hello!

I seem to be having trouble setting up CCDD so that I can utilize Python + Py4J to export my tables. I've followed the directions as outlined in Section 3.3 in the [Installation Guide](https://github.com/nasa/CCDD/blob/CCDD-2/Docs/CCDD_Installation_Guide.pdf) but still get an `extension not supported` error.

I am using CCDD 2.1.7 and Python 3.10.13 with the latest release of Py4J; a docker container is hosting the Postgres DB on port 5432. 

I'm assuming I must be doing something wrong with setting up the environment variable for Py4J because of
https://github.com/nasa/CCDD/blob/4a4d748089e9fb4a4de53c0c8cf86ca509b66861/src/CCDD/CcddScriptHandler.java#L195-L207
but I cannot figure out what it is that I've done wrong. 

Below are relevant snippets from the log file.

```
127.0.0.1:5432|*none*|ccdd_db|02/21/2024 19:03:20.772|Status|CCDD: 2.1.7 (2-21-2024)  ***  Java: 21.0.2 (64-bit) *** command line: -host 127.0.0.1 -port 5432 
127.0.0.1:5432|MyProject|ccdd_db|02/21/2024 19:03:35.177|Fail|Cannot execute script '$PROJECT_DIR/scripts/cosmos.py' using table(s) 'Group:All tables'; cause 'Script file '$PROJECT_DIR/scripts/cosmos.py' extension is unsupported'
```

The python script I'm trying out is simply:
```python
# Import the script data access method class
from CCDD import CcddScriptDataAccessHandler

# Open the output file
file = ccdd.openOutputFile("./myFileName")

# Get the array of structure names
structNames = ccdd.getStructureTableNames()

# Step through each name found
for index in range(len(structNames)):
    # Write the structure name to the output file
    print(index)
    ccdd.writeToFileLn(file, "structNames[" + str(index) + "] = " + structNames[index])

# Close the output file
ccdd.closeFile(file)

```

Can you please advise if I missed something with the setup? Thank you for your help!

**Comment by KevinMcCluney** [comment]
The issue is that CCDD is not locating the py4j .jar library.  If you can build CCDD then the .jar file can be incorporated into the class path.  Otherwise, you need to supply the path to the file.  There are two ways to specify the class path:
1. Copy the py4j .jar file (e.g., `py4j0.10.9.7.jar`)  to the `CCDD_lib` folder.  Then start CCDD using:
`java -classpath CCDD.jar:CCDD_lib/* CCDD.CcddMain`
2. Start CCDD using:
`java -classpath CCDD.jar:CCDD_lib/*:/path/to/the/jar/file/py4j0.10.9.7.jar CCDD.CcddMain`
Both of these methods assume that the `CCDD_lib` folder is in the same location as `CCDD.jar`.

**Comment by kadri-nizam** [comment]
That worked!! Just had to alter the script to use the Py4J tutorial version instead of the Jython one which I included above. 😅 

Thank you so much for your help!
