### ISSUE TITLE
Feature Request: Input datatype for existing structure rows

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#21]
It would be useful to have a input data type which validated that the input is a structure row which already exists in the database. The use case is for defining data products which depend on existing definitions (or properties of those definitions) in the database, such as:

-  defining CCDD table types which describe CFS limit checker tables. Limit checker tables define the value to be checked in terms of the apid and packet offset, both of which are already available from CCDD given a valid structure row. 
- defining CCDD table types which describe CFS HK tables. HK tables define the value to place in a new packet by Apid and packet offset, similar to above.

Having the entry field validate the entry is an existing row in the database greatly simplifies the error checking necessary in the scripts to generate these products.

As a user-convenience feature, it would also be great if the input field could prompt/autocomplete a user typing the name/path of the mnemonic to make it easier to enter this data.

Thanks for the consideration.

**Comment by KevinMcCluney** [comment]
In the latest version (1.3.8) there is a new input type, Variable reference.  A table cell or data field with this input type displays a combo box showing every current variable, including the full table path.  Does this cover what you want?

The added input type should be considered experimental at this point - if a variable name is changed or a variable is deleted then any cell/field of this input type that references the variable is unchanged (the background should turn yellow to indicate it isn't a part of the list).

**Comment by ascended121** [comment]
Thanks Kevin. Been attempting to test out the new input type... could you confirm that I should be able to get the value of the field via the getTableData API method? I'm getting an empty return when querying a Variable Reference column. Could be an issue with my script/table setup though.

Provided I can get my script working, I think the Variable Reference input type does cover my use case. I think the functionality is there... the following suggestions are only to improve usability:

Current for even a mid-size system there are a lot of options, which can be a bit time consuming to scroll through. I think the most useful enhancement would be to autofill/filter based on user entry (ie, show the list, but if the user starts typing remove all the results which don't match what the user began to type). 

Can you explain why CCDD variable path's also contain the datatype of the field? The default structure table requires the variable name field to be unique, so it seems like just a hierarchical listing of the names (ie, parent.child.variable) should be enough to specify the path to the variable. Removing the datatypes from the path displayed would reduce the length of the path (which makes them quicker/easier to read), however I think that there might be value in keeping it consistent with other CCDD paths which makes removing the datatype undesirable if that's the standard that CCDD uses.

**Comment by ascended121** [comment]
Can confirm that getTableData works as expected with the Variable Reference input type... I was just calling it incorrectly.

**Comment by KevinMcCluney** [comment]
I was able to add the variable list functionality quickly since that list is already maintained by CCDD.  If you look at the dialog produced by "Data | Show variables" you'll see the exact same list (in the "Application Format" column).  Internally, the application requires the variable and data type in the table paths for numerous reasons.  Since the combo box menu doesn't require the data types, I altered the combo box list so that the data types are extracted from the paths.  This will show up in version 1.3.9.

Auto-completion for the variable reference input type is non-trivial.  I'll look into it.

**Comment by KevinMcCluney** [comment]
Auto-completion will be enabled for table cells and data fields that display a list of items from which to choose (via a combo box menu) beginning with version 1.3.11.

**Comment by ascended121** [comment]
Hey Kevin, thanks for looking into this. 

The current implementation of the autocomplete appears to fill the first entry that matches what the user has typed, which is helpful but may not be the entry the user is looking for. While typing, if I click the down error the dropdown spawns but doesn't contain an entry which matches what I'm typing, making it hard to navigate if I'm not exactly sure what I'm looking for.

It would be helpful if typing in this field created a drop down with all the current options that match what the user has typed so that they can see the options change as they type.

An example of this would be, for a project containing the following tables:

mytbl1,value1
mytbl1,othervalue
mytbl1,subtable1.value1
mytbl1,subtable1.othervalue
mytbl2,value1
mytbl2,othervalue
myothertbl,value1
myothertbl,value2

When the user selected the field/started typing, a dropdown would appear containing mytbl1, mytbl2, and myothertable. The user would be able to use the up/down arrow keys to select one of the options quickly, or continue typing to further refine the list. The dropdown would remain the same if the user typed 'my' (because 'my' matches all three options), but as soon as the user had entered 'myt' only mytbl1 and mytbl2 would be shown. 

If the user selects an option using the arrow keys, that option would be filled into the field (ie, if the user had typed 'myt' but then selected 'mytbl2' using the arrow keys, fill the field with 'mytbl2' so that the user doesn't have to type the rest). If that selection has additional options (ie, 'mytbl2' has the children 'value1' and 'othervalue'), a comma would be appended (so that field reads 'mytbl2,' and the dropdown now contains all the options which match it (ie, the children of 'mytbl2') so that the user can immediately begin typing/selecting a subfield).

I realize this is probably more complicated to implement but I think it makes it really easy and efficient for users to navigate through a large project.

**Comment by KevinMcCluney** [comment]
As the user types, what you should be seeing is the typed text followed by the remaining text, highlighted, of the first matching item.  If the menu it displayed ('dropped down') then the list automatically scrolls to the first matching item as the user types (I just noticed the auto-scroll isn't working for Java 8 - I've found a 'fix', which will be uploaded by COB today).

I initially implemented the auto-completion so that the drop down menu item list was pruned to only those items beginning with the text entered.  However, updating the list to achieve this involves a time-intensive operation buried within Java that I was unable to get around.

**Comment by KevinMcCluney** [comment]
Update: I found a way to prune the item list without incurring a huge time lag (tested with >11,000 list items).  I've modified the behavior of the drop down menus so that items not matching the entered text are removed.  Wildcard characters are allowed - a '?' matches a single character and a '*' matches one or more characters.  An '*' is assumed to be at the end of the entered text (so, for example, if you type 'q' then any item beginning with a 'q' remains in the list).  This feature will be available in the next release.
