### ISSUE TITLE
Feature Request: Methods to query global structure tables

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#23]
According to the documentation, the getStructureTableNumRows() scripting method is intended to return the number of rows in the structure table. In the built-in scripts this method is used to get the structure rows for the tables passed as arguments to the current script execution. It might be helpful to clarify this in the documentation (ie, that this methods does not returns the global number of structure rows, just the ones passed to the script). 

It would be helpful to have script methods which are capable of querying the whole database, rather than just the elements passed to the script. This could be achieved either via specialized methods or optional arguments to existing methods.

I'm prototyping generating cFS HK tables via a custom table type which includes the name/path of the variables (in the CCDD database) which should be included in a particular HK-generated packet. Using the variable name to retrieve the Message ID and Byte Offset via scripts requires access to the rest of the database, which can currently only be achieved by calling the script on every available structure table. Global database query methods (and input validations such as issue #21) enable workflows in which tables refer to other elements in the database (such as for Limit Checker and HK tables).

**Comment by KevinMcCluney** [comment]
The getStructureTableNumRows() method returns the total number of rows for all tables associated with the script that represent a structure.  CCDD concatenates tables of the same type together.  The method getStructurePathByRow() can be used to determine what structure table a particular row belongs to.

Part of the rationale for associating tables with a script is to control what data the script is working with.  If the script requires access to all table data then all tables can be associated with it.  The current way the data is handled doesn't require the script to have the table names and paths hard-coded within them (this information is provided by the associated tables themselves).

If you have a need for some specific global (or otherwise) methods please submit the requirements (inputs & output) and I'll see about adding them.  Your description regarding the HK tables sounds similar to what is done using the telemetry scheduler and its associated script (copyTable.__).

**Comment by ascended121** [comment]
I think the current association system is sufficient and that the Tables 9 and 10 are helpful for clarifying the scope of the scripting methods. I think this issue can be closed. Appreciate the consideration!
