### ISSUE TITLE
Unable to delete redundant macro definitions

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#43]
I've ended up in a situation where I have duplicate macro definitions (through the import process, though I'm unsure if it may have been my fault). I'm unable to delete any of the duplicate definitions because the gui says that they're referenced by a table (which is true). 

It would be helpful if the import process could merge completely identical macro definitions and either prompt or throw an error for different macro definitions with the same name (to allow the user to sort it out). It would also be helpful for the GUI to allow deleting macros (even if they're referenced by a table) as long as at least one macro with that name still exists.

Thanks!

**Comment by KevinMcCluney** [comment]
When importing macros the macro name is used to determine if the macro already exists; if so the values of the existing and imported macro are compared.  If the values differ an error dialog appears ("Imported macro '_macro name_' doesn't match the existing definition").  Since it isn't (or shouldn't be) possible for a duplicate to exist I don't feel that a method to delete duplicates is needed.  You can temporarily replace the macro references in the affected tables, remove the duplicate macro definitions, and then restore the macros in the tables.   As an alternative you can use the PostgreSQL command line utility, **psql**, to manually edit the macro table:
   SELECT *,OID FROM __macros;
   DELETE FROM __macros WHERE OID = '_OID # of macro to delete_';

I did find a way to create a duplicate macro definition - by having the definition appear more than once in the import file(s).  That is addressed in the next release (1.4.37).

**Comment by ascended121** [comment]
Thanks, sounds reasonable not to add a method of deleting duplicates if that's a corner case that there are already protections against. The import protection sounds like it'll solve the problem for me anyways next time I import.

Thanks!

**Comment by KevinMcCluney** [comment]
I missed the comment regarding duplicate macros in the JSON export.  This is corrected in the latest version (1.4.44); the CSV export was also affected and fixed.

**Comment by ascended121** [comment]
I'm not observing this issue any longer (at least in the exported json, haven't tested CSV) in 1.14.48. Thanks!
