### ISSUE TITLE
Command-line script execution documentation appears to be inaccurate

### ISSUE THREAD

**Issue by ascended121** [nasa/CCDD#6]
Section 4.6.10 of the user guide documents how to execute a script from the command line. Documentation states that the argument format of `-execute <script_name>:<table>` or  `-execute <script_name>:Group:<group_name>`. Argument format appears to actually be `-execute <script_association_name>:<script_name>:<table>` or `-execute <script_association_name>:<script_name>:Group:<group_name>`.

Attempting to run `-execute myScript:myTable` results in `Cannot execute script ‘myTable’ using table(s) ' '`. Running `-execute myAssociation:myScript:myTable` completes successfully. Using a myAssociation not in the database results in an error "Unrecognized association name".

Also, documentation states that script path is required if they’re not stored in the same location as the CCDD executes, however commands without path succeed for scripts located in the /scripts directory (did not test with other locations).

Observed on CCDD version "1.1.46 1-11-2018" cloned from git on 1/16/18.

**Comment by KevinMcCluney** [comment]
An update has been uploaded (on 1/22/2018) to address the command line format issue.  The -execute command now behaves as described in the user's guide.

If an association is used in the -execute command then no path is needed since the path is embedded in the association.  However, if a script is specified then it requires a path.  I suspect the other issue resulted in this behavior since you had to include an association as well as the script reference.  With the correction the need for a path follows what's in the guide.
