### ISSUE TITLE
Question about automatic message ID assignments

### ISSUE THREAD

**Issue by royerboat** [nasa/CCDD#86]
Sorry, this isn't really a bug and more of a question. If this isn't the right avenue to ask this, let me know and I will redirect this question to another place.

I'm a bit confused by the Assign IDs functionality. After reading the tutorial, it seems like this functionality gets applied to the "Message ID" field. But in reality, this field seems to be the "Telemetry message name & ID" and "Command  name & ID" fields.

Is there a way to provide a group which represents a CFS application, a message ID prefix. Say I have 2 groups which represent app1 and app2. I want the message IDs for app1 to start with 0x09a and app2 to start with 0x0aa. Is there a way to set prefixes like that for individual groups?

Also what about if I have a structure that I don't want to get an assigned message ID? Should I just put a # in that field to avoid the automatic assignment?

**Comment by bawi235** [comment]
This avenue works fine for questions like these. Let me look into this and get back to you.

**Comment by bawi235** [comment]
I am working on a solution to this request. It may not come for a few more days though as I am low on hours for the CCDD project. Will post here as soon as I push the updates.

**Comment by bawi235** [comment]
I have refactored the assign message ID dialog and functionality. You now have a table tree to select from which gives you the ability to select and table, group or table type you wish to update. If you wish not to assign a message ID to a table then leave it out of your selection. I will leave this issue open for now so that you can comment here if you encounter any problems with this new functionality.

**Comment by bawi235** [comment]
As for the group prefixes you can update the IDs of each group one by one and change the starting ID each time. You can also change the interval if you do not wish for it to increment by 1 after each ID is assigned.
